package com.armygame.recruits.xml.parsestates;

/**
 * Title: AnimationsManifests
 * Description: Auto generated concrete <code>DocumentParseState</code>
 * Copyright:    Copyright (c) 2001
 * Company:
 * @author Neal Elzenga (Auto Generated)
 * @version 1.0
 */
import org.xml.sax.Attributes;
import com.armygame.recruits.xml.ParserStateMachine;
import com.armygame.recruits.xml.DocumentParseState;

/**
 * Class for handling XML AnimationsManifests tags.  This class is a <b>Singleton</b>
 * (see 'Design Patterns' - Gamma et. al)
 * <b>IMPORTANT NOTE:</b> This class was auto generated by the
 * <b>MakeStates</b> tool, and requires user customization of the
 * following methods:
 * <code>InitializeState()</code>, <code>StartElement()</code>,
 * <code>EndElement</code>, <code>Characters</code>
 */
public class AnimationsManifests extends DocumentParseState {

  /**
   * The single AnimationsManifests
   */
  private static AnimationsManifests theirInstance = null;

  /**
   * The constructor is <code>private</code> to enforce <b>Singleton</b>
   * behavior
   */
  private AnimationsManifests() {
  }

  /**
   * Return the AnimationsManifests <b>Singleton</b>
   * @return The AnimationsManifests <b>Singleton</b>
   */
  public static AnimationsManifests Instance() {
    if( theirInstance == null ) {
      theirInstance = new AnimationsManifests();
    }
    return theirInstance;
  }

}
