package com.armygame.recruits.xml.parsestates;

/**
 * Title: LocationMediaElement
 * Description: Auto generated concrete <code>DocumentParseState</code>
 * Copyright:    Copyright (c) 2001
 * Company:
 * @author Neal Elzenga (Auto Generated)
 * @version 1.0
 */
import org.xml.sax.Attributes;

import com.armygame.recruits.globals.RecruitsPackageConstants;
import com.armygame.recruits.utils.StateVector;
import com.armygame.recruits.utils.TargetObjectKey;
import com.armygame.recruits.xml.ParserStateMachine;
import com.armygame.recruits.xml.DocumentParseState;
import com.armygame.recruits.xml.ConstructorCall;
import com.armygame.recruits.xml.EndConstructorSentinel;
import com.armygame.recruits.xml.ConstructionMethodCall;
import com.armygame.recruits.xml.EndMethodCallSentinel;
import com.armygame.recruits.xml.MakeArgumentFromStackTopSentinel;


/**
 * Class for handling XML LocationMediaElement tags.  This class is a <b>Singleton</b>
 * (see 'Design Patterns' - Gamma et. al)
 * <b>IMPORTANT NOTE:</b> This class was auto generated by the
 * <b>MakeStates</b> tool, and requires user customization of the
 * following methods:
 * <code>InitializeState()</code>, <code>StartElement()</code>,
 * <code>EndElement</code>, <code>Characters</code>
 */
public class LocationMediaElement extends DocumentParseState implements RecruitsPackageConstants {

  /**
   * The single LocationMediaElement
   */
  private static LocationMediaElement theirInstance = null;

  /**
   * The constructor is <code>private</code> to enforce <b>Singleton</b>
   * behavior
   */
  private LocationMediaElement() {
    super();
  }

  /**
   * Return the LocationMediaElement <b>Singleton</b>
   * @return The LocationMediaElement <b>Singleton</b>
   */
  public static LocationMediaElement Instance() {
    if( theirInstance == null ) {
      theirInstance = new LocationMediaElement();
    }
    return theirInstance;
  }

  /**
   * This state is called when a <b>&lt;LocationMediaElement&gt;</b> element is parsed.
   * @param context The <code>ParserStateMachine</code> that is managing our parsing
   */
  public void InitializeState( ParserStateMachine context ) {
    context.AddConstructionTask( new ConstructionMethodCall( "Insert", new Class[] { TargetObjectKey.class, String.class } ) );
    // System.out.println( "Would have called Insert()" );
  }

  /**
   * This state is called when we get the end element for state LocationMediaElement
   * @param context The <code>ParserStateMachine</code> that is managing our parsing
   * @param uri
   * @param localName
   * @param qName
   * @see org.xml.SAX#endElement()
   */
  public void EndElement( ParserStateMachine context, String uri, String localName, String qName ) {
    context.AddConstructionTask( new EndMethodCallSentinel() );
    // System.out.println( "End Sentinel for would have called Insert()" );
  }

}
