package com.armygame.recruits.xml.parsestates;

/**
 * Title: LocationTemplateFile
 * Description: Auto generated concrete <code>DocumentParseState</code>
 * Copyright:    Copyright (c) 2001
 * Company:
 * @author Neal Elzenga (Auto Generated)
 * @version 1.0
 */
import org.xml.sax.Attributes;

import com.armygame.recruits.globals.RecruitsPackageConstants;
import com.armygame.recruits.xml.ParserStateMachine;
import com.armygame.recruits.xml.DocumentParseState;
import com.armygame.recruits.xml.ConstructorCall;
import com.armygame.recruits.xml.EndConstructorSentinel;
import com.armygame.recruits.xml.ConstructionMethodCall;
import com.armygame.recruits.xml.EndMethodCallSentinel;
import com.armygame.recruits.xml.MakeArgumentFromStackTopSentinel;
import com.armygame.recruits.xml.StringArgument;


/**
 * Class for handling XML LocationTemplateFile tags.  This class is a <b>Singleton</b>
 * (see 'Design Patterns' - Gamma et. al)
 * <b>IMPORTANT NOTE:</b> This class was auto generated by the
 * <b>MakeStates</b> tool, and requires user customization of the
 * following methods:
 * <code>InitializeState()</code>, <code>StartElement()</code>,
 * <code>EndElement</code>, <code>Characters</code>
 */
public class LocationTemplateFile extends DocumentParseState implements RecruitsPackageConstants {

  /**
   * The single LocationTemplateFile
   */
  private static LocationTemplateFile theirInstance = null;

  /**
   * The constructor is <code>private</code> to enforce <b>Singleton</b>
   * behavior
   */
  private LocationTemplateFile() {
    super();
  }

  /**
   * Return the LocationTemplateFile <b>Singleton</b>
   * @return The LocationTemplateFile <b>Singleton</b>
   */
  public static LocationTemplateFile Instance() {
    if( theirInstance == null ) {
      theirInstance = new LocationTemplateFile();
    }
    return theirInstance;
  }

  /**
   * This state is called when we get the end element for state LocationTemplateFile
   * @param context The <code>ParserStateMachine</code> that is managing our parsing
   * @param uri
   * @param localName
   * @param qName
   * @see org.xml.SAX#endElement()
   */
  public void EndElement( ParserStateMachine context, String uri, String localName, String qName ) {
    context.AddConstructionTask( new ConstructionMethodCall( "SetTargetObject", new Class[] { Object.class } ) );
    context.AddConstructionTask( new StringArgument( context.GetCharBuffer() ) );
    context.AddConstructionTask( new EndMethodCallSentinel() );
    context.AddConstructionTask( new EndConstructorSentinel() );
    // context.AddConstructionTask( new StringArgument( context.RecallTagValue( "RoleName" ) ) );
    context.AddConstructionTask( new MakeArgumentFromStackTopSentinel() );
  }

}
