package com.armygame.recruits.xml.parsestates;

/**
 * Title: RangeMapDef
 * Description: Auto generated concrete <code>DocumentParseState</code>
 * Copyright:    Copyright (c) 2001
 * Company:
 * @author Neal Elzenga (Auto Generated)
 * @version 1.0
 */
import org.xml.sax.Attributes;

import com.armygame.recruits.globals.RecruitsPackageConstants;
import com.armygame.recruits.utils.RangeMap;
import com.armygame.recruits.xml.ParserStateMachine;
import com.armygame.recruits.xml.DocumentParseState;
import com.armygame.recruits.xml.ConstructionMethodCall;
import com.armygame.recruits.xml.EndMethodCallSentinel;


/**
 * Class for handling XML RangeMapDef tags.  This class is a <b>Singleton</b>
 * (see 'Design Patterns' - Gamma et. al)
 * <b>IMPORTANT NOTE:</b> This class was auto generated by the
 * <b>MakeStates</b> tool, and requires user customization of the
 * following methods:
 * <code>InitializeState()</code>, <code>StartElement()</code>,
 * <code>EndElement</code>, <code>Characters</code>
 */
public class RangeMapDef extends DocumentParseState implements RecruitsPackageConstants {

  /**
   * The single RangeMapDef
   */
  private static RangeMapDef theirInstance = null;

  /**
   * The constructor is <code>private</code> to enforce <b>Singleton</b>
   * behavior
   */
  private RangeMapDef() {
    super();
  }

  /**
   * Return the RangeMapDef <b>Singleton</b>
   * @return The RangeMapDef <b>Singleton</b>
   */
  public static RangeMapDef Instance() {
    if( theirInstance == null ) {
      theirInstance = new RangeMapDef();
    }
    return theirInstance;
  }

  /**
   * This state is called when a <b>&lt;RangeMapDef&gt;</b> element is parsed.
   * @param context The <code>ParserStateMachine</code> that is managing our parsing
   */
  public void InitializeState( ParserStateMachine context ) {
    context.AddConstructionTask( new ConstructionMethodCall( "AddRangeMap", new Class[] { String.class, RangeMap.class } ) );
  }

  /**
   * This state is called when we get the end element for state RangeMapDef
   * @param context The <code>ParserStateMachine</code> that is managing our parsing
   * @param uri
   * @param localName
   * @param qName
   * @see org.xml.SAX#endElement()
   */
  public void EndElement( ParserStateMachine context, String uri, String localName, String qName ) {
    context.AddConstructionTask( new EndMethodCallSentinel() );
  }

}
