package com.armygame.recruits.xml.parsestates;

/**
 * Title: RangeDefinitions
 * Description: Auto generated concrete <code>DocumentParseState</code>
 * Copyright:    Copyright (c) 2001
 * Company:
 * @author Neal Elzenga (Auto Generated)
 * @version 1.0
 */
import org.xml.sax.Attributes;
import com.armygame.recruits.xml.ParserStateMachine;
import com.armygame.recruits.xml.DocumentParseState;
import com.armygame.recruits.xml.IntArgument;

/**
 * Class for handling XML RangeDefinitions tags.  This class is a <b>Singleton</b>
 * (see 'Design Patterns' - Gamma et. al)
 * <b>IMPORTANT NOTE:</b> This class was auto generated by the
 * <b>MakeStates</b> tool, and requires user customization of the
 * following methods:
 * <code>InitializeState()</code>, <code>StartElement()</code>,
 * <code>EndElement</code>, <code>Characters</code>
 */
public class RangeDefinitions extends com.armygame.recruits.xml.DocumentParseState {

  /**
   * The single RangeDefinitions
   */
  private static RangeDefinitions theirInstance = null;

  /**
   * The constructor is <code>private</code> to enforce <b>Singleton</b>
   * behavior
   */
  private RangeDefinitions() {
    super();
  }

  /**
   * Return the RangeDefinitions <b>Singleton</b>
   * @return The RangeDefinitions <b>Singleton</b>
   */
  public static RangeDefinitions Instance() {
    if( theirInstance == null ) {
      theirInstance = new RangeDefinitions();
    }
    return theirInstance;
  }

}
