package com.armygame.recruits.xml.parsestates;

/**
 * Title: RangeMap
 * Description: Auto generated concrete <code>DocumentParseState</code>
 * Copyright:    Copyright (c) 2001
 * Company:
 * @author Neal Elzenga (Auto Generated)
 * @version 1.0
 */
import org.xml.sax.Attributes;
import com.armygame.recruits.globals.RecruitsPackageConstants;
import com.armygame.recruits.xml.ParserStateMachine;
import com.armygame.recruits.xml.DocumentParseState;
import com.armygame.recruits.xml.ConstructorCall;
import com.armygame.recruits.xml.EndConstructorSentinel;
import com.armygame.recruits.xml.SaveObjectForReturnSentinel;


/**
 * Class for handling XML RangeMap tags.  This class is a <b>Singleton</b>
 * (see 'Design Patterns' - Gamma et. al)
 * <b>IMPORTANT NOTE:</b> This class was auto generated by the
 * <b>MakeStates</b> tool, and requires user customization of the
 * following methods:
 * <code>InitializeState()</code>, <code>StartElement()</code>,
 * <code>EndElement</code>, <code>Characters</code>
 */
public class RangeMap extends DocumentParseState implements RecruitsPackageConstants {

  /**
   * The single RangeMap
   */
  private static RangeMap theirInstance = null;

  /**
   * The constructor is <code>private</code> to enforce <b>Singleton</b>
   * behavior
   */
  private RangeMap() {
    super();
  }

  /**
   * Return the RangeMap <b>Singleton</b>
   * @return The RangeMap <b>Singleton</b>
   */
  public static RangeMap Instance() {
    if( theirInstance == null ) {
      theirInstance = new RangeMap();
    }
    return theirInstance;
  }

  /**
   * This state is called when a <b>&lt;RangeMap&gt;</b> element is parsed.
   * @param context The <code>ParserStateMachine</code> that is managing our parsing
   */
  public void InitializeState( ParserStateMachine context ) {
    // context.AddConstructionTask( new ConstructorCall( UTILS_PACKAGE, "RangeMap" ) );
  }

  /**
   * This state is called when we get the end element for state RangeMap
   * @param context The <code>ParserStateMachine</code> that is managing our parsing
   * @param uri
   * @param localName
   * @param qName
   * @see org.xml.SAX#endElement()
   */
  public void EndElement( ParserStateMachine context, String uri, String localName, String qName ) {
    // context.AddConstructionTask( new EndConstructorSentinel() );
    context.AddConstructionTask( new SaveObjectForReturnSentinel() );
  }

}
