package com.armygame.recruits.xml.parsestates;

/**
 * Title: RangeMapFile
 * Description: Auto generated concrete <code>DocumentParseState</code>
 * Copyright:    Copyright (c) 2001
 * Company:
 * @author Neal Elzenga (Auto Generated)
 * @version 1.0
 */
import org.xml.sax.Attributes;

import com.armygame.recruits.utils.RangeMap;
import com.armygame.recruits.globals.RecruitsGame;
import com.armygame.recruits.globals.RecruitsConfiguration;
import com.armygame.recruits.xml.ParserStateMachine;
import com.armygame.recruits.xml.DocumentParseState;
import com.armygame.recruits.xml.ObjectArgument;


/**
 * Class for handling XML RangeMapFile tags.  This class is a <b>Singleton</b>
 * (see 'Design Patterns' - Gamma et. al)
 * <b>IMPORTANT NOTE:</b> This class was auto generated by the
 * <b>MakeStates</b> tool, and requires user customization of the
 * following methods:
 * <code>InitializeState()</code>, <code>StartElement()</code>,
 * <code>EndElement</code>, <code>Characters</code>
 */
public class RangeMapFile extends DocumentParseState {

  /**
   * The single RangeMapFile
   */
  private static RangeMapFile theirInstance = null;

  /**
   * The constructor is <code>private</code> to enforce <b>Singleton</b>
   * behavior
   */
  private RangeMapFile() {
    super();
  }

  /**
   * Return the RangeMapFile <b>Singleton</b>
   * @return The RangeMapFile <b>Singleton</b>
   */
  public static RangeMapFile Instance() {
    if( theirInstance == null ) {
      theirInstance = new RangeMapFile();
    }
    return theirInstance;
  }

  /**
   * This state is called when we get the end element for state RangeMapFile
   * @param context The <code>ParserStateMachine</code> that is managing our parsing
   * @param uri
   * @param localName
   * @param qName
   * @see org.xml.SAX#endElement()
   */
  public void EndElement( ParserStateMachine context, String uri, String localName, String qName ) {
    RangeMap ReadRangeMap = new RangeMap();
    RecruitsConfiguration CurrentConfiguration = RecruitsGame.Instance().Configuration();
    ReadRangeMap.ParseXMLObject( CurrentConfiguration.MakeFullPath( CurrentConfiguration.RangeMapsPath(), context.GetCharBuffer() ) );
    context.AddConstructionTask( new ObjectArgument( ReadRangeMap ) );
  }

}
