package com.armygame.recruits.xml.parsestates;

/**
 * Title: RegistrationPoint
 * Description: Auto generated concrete <code>DocumentParseState</code>
 * Copyright:    Copyright (c) 2001
 * Company:
 * @author Neal Elzenga (Auto Generated)
 * @version 1.0
 */
import org.xml.sax.Attributes;

import com.armygame.recruits.globals.RecruitsPackageConstants;
import com.armygame.recruits.xml.ParserStateMachine;
import com.armygame.recruits.xml.DocumentParseState;
import com.armygame.recruits.xml.ConstructorCall;
import com.armygame.recruits.xml.EndConstructorSentinel;
import com.armygame.recruits.xml.ConstructionMethodCall;
import com.armygame.recruits.xml.EndMethodCallSentinel;
import com.armygame.recruits.xml.MakeArgumentFromStackTopSentinel;


// import com.armygame.recruits.mediaelements.RegistrationPoint;

/**
 * Class for handling XML RegistrationPoint tags.  This class is a <b>Singleton</b>
 * (see 'Design Patterns' - Gamma et. al)
 * <b>IMPORTANT NOTE:</b> This class was auto generated by the
 * <b>MakeStates</b> tool, and requires user customization of the
 * following methods:
 * <code>InitializeState()</code>, <code>StartElement()</code>,
 * <code>EndElement</code>, <code>Characters</code>
 */
public class RegistrationPoint extends DocumentParseState implements RecruitsPackageConstants {

  /**
   * The single RegistrationPoint
   */
  private static RegistrationPoint theirInstance = null;

  /**
   * The constructor is <code>private</code> to enforce <b>Singleton</b>
   * behavior
   */
  private RegistrationPoint() {
    super();
  }

  /**
   * Return the RegistrationPoint <b>Singleton</b>
   * @return The RegistrationPoint <b>Singleton</b>
   */
  public static RegistrationPoint Instance() {
    if( theirInstance == null ) {
      theirInstance = new RegistrationPoint();
    }
    return theirInstance;
  }

  /**
   * This state is called when a <b>&lt;RegistrationPoint&gt;</b> element is parsed.
   * @param context The <code>ParserStateMachine</code> that is managing our parsing
   */
  public void InitializeState( ParserStateMachine context ) {
    context.AddConstructionTask( new ConstructionMethodCall( "SetRegistrationPoint", new Class[] { com.armygame.recruits.mediaelements.RegistrationPoint.class } ) );
    context.AddConstructionTask( new ConstructorCall( MEDIAELEMENTS_PACKAGE, "RegistrationPoint" ) );
  }

  /**
   * This state is called when we get the end element for state RegistrationPoint
   * @param context The <code>ParserStateMachine</code> that is managing our parsing
   * @param uri
   * @param localName
   * @param qName
   * @see org.xml.SAX#endElement()
   */
  public void EndElement( ParserStateMachine context, String uri, String localName, String qName ) {
    context.AddConstructionTask( new EndConstructorSentinel() );
    context.AddConstructionTask( new MakeArgumentFromStackTopSentinel() );
    context.AddConstructionTask( new EndMethodCallSentinel() );
  }

}
