package com.armygame.recruits.xml.parsestates;

/**
 * Title: Sentence
 * Description: Auto generated concrete <code>DocumentParseState</code>
 * Copyright:    Copyright (c) 2001
 * Company:
 * @author Neal Elzenga (Auto Generated)
 * @version 1.0
 */
import org.xml.sax.Attributes;
import com.armygame.recruits.globals.RecruitsPackageConstants;
import com.armygame.recruits.xml.ParserStateMachine;
import com.armygame.recruits.xml.DocumentParseState;
import com.armygame.recruits.xml.ConstructionMethodCall;
import com.armygame.recruits.xml.EndMethodCallSentinel;
import com.armygame.recruits.xml.StringArgument;


/**
 * Class for handling XML Sentence tags.  This class is a <b>Singleton</b>
 * (see 'Design Patterns' - Gamma et. al)
 * <b>IMPORTANT NOTE:</b> This class was auto generated by the
 * <b>MakeStates</b> tool, and requires user customization of the
 * following methods:
 * <code>InitializeState()</code>, <code>StartElement()</code>,
 * <code>EndElement</code>, <code>Characters</code>
 */
public class Sentence extends DocumentParseState implements RecruitsPackageConstants {

  /**
   * The single Sentence
   */
  private static Sentence theirInstance = null;

  /**
   * The constructor is <code>private</code> to enforce <b>Singleton</b>
   * behavior
   */
  private Sentence() {
    super();
  }

  /**
   * Return the Sentence <b>Singleton</b>
   * @return The Sentence <b>Singleton</b>
   */
  public static Sentence Instance() {
    if( theirInstance == null ) {
      theirInstance = new Sentence();
    }
    return theirInstance;
  }


  /**
   * This state is called when we get the end element for state Sentence
   * @param context The <code>ParserStateMachine</code> that is managing our parsing
   * @param uri
   * @param localName
   * @param qName
   * @see org.xml.SAX#endElement()
   */
  public void EndElement( ParserStateMachine context, String uri, String localName, String qName ) {
    // Fold the template name and range map into the template
    context.AddConstructionTask( new ConstructionMethodCall( "DefineSentence", new Class[] { String.class, String.class , String.class } ) );
    context.AddConstructionTask( new StringArgument( context.RecallTagValue( "DescriptiveName" ) ) );
    context.AddConstructionTask( new StringArgument( context.RecallTagValue( "SpeechName" ) ) );
    context.AddConstructionTask( new StringArgument( context.RecallTagValue( "SentenceGrammar" ) ) );
    context.AddConstructionTask( new EndMethodCallSentinel() );
  }

}
